name: Deploy to Azure

on:
  push:
    branches: [ "main" ]  # Déclencheur : push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du code
      - uses: actions/checkout@v4

      # Étape 2 : Configurer Node.js (exemple)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Étape 3 : Installer les dépendances et build
      - name: npm install and build
        run: |
          npm install
          npm run build  # Si nécessaire (ex: React, Angular)

      # Étape 4 : Déployer sur Azure Web App
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .  # Dossier à déployer (ou 'dist' si SPA)